-- 027: Seed the mantra library and Learn articles with real content.
insert into public.mantras (slug, name, name_devanagari, deity, transliteration, meaning_i18n, featured, status) values
('gayatri-mantra','Gayatri Mantra','ॐ भूर्भुवः स्वः । तत्सवितुर्वरेण्यं भर्गो देवस्य धीमहि । धियो यो नः प्रचोदयात् ॥','Savitr / Divine Light','Om bhūr bhuvaḥ svaḥ, tat savitur vareṇyaṃ, bhargo devasya dhīmahi, dhiyo yo naḥ pracodayāt','{"en": "We meditate on the glorious divine light of the source of all creation; may it illumine our understanding."}'::jsonb, true, 'published'),
('maha-mrityunjaya','Maha Mrityunjaya Mantra','ॐ त्र्यम्बकं यजामहे सुगन्धिं पुष्टिवर्धनम् । उर्वारुकमिव बन्धनान्मृत्योर्मुक्षीय मामृतात् ॥','Shiva','Om tryambakaṃ yajāmahe sugandhiṃ puṣṭivardhanam, urvārukamiva bandhanān mṛtyor mukṣīya māmṛtāt','{"en": "We worship the three-eyed Lord who nourishes all beings; may he free us from the bondage of mortality, as a ripe fruit frees itself from the vine."}'::jsonb, true, 'published'),
('om-namah-shivaya','Om Namah Shivaya','ॐ नमः शिवाय','Shiva','Om namaḥ śivāya','{"en": "I bow to Shiva — the auspicious consciousness that pervades all."}'::jsonb, true, 'published'),
('guru-brahma','Guru Invocation','गुरुर्ब्रह्मा ग्रुरुर्विष्णुः गुरुर्देवो महेश्वरः । गुरुः साक्षात् परं ब्रह्म तस्मै श्री गुरवे नमः ॥','The Guru','Gurur brahmā gurur viṣṇuḥ gurur devo maheśvaraḥ, guruḥ sākṣāt paraṃ brahma tasmai śrī gurave namaḥ','{"en": "The guru is Brahma, Vishnu and Maheshwara — the supreme reality itself. Salutations to that sacred teacher."}'::jsonb, false, 'published'),
('shanti-mantra','Shanti Mantra','ॐ शान्तिः शान्तिः शान्तिः','Universal Peace','Om śāntiḥ śāntiḥ śāntiḥ','{"en": "Peace in the self, peace in the world around, peace in the divine."}'::jsonb, false, 'published')
on conflict (slug) do nothing;

insert into public.articles (slug, title_i18n, excerpt_i18n, body_i18n, level, source_type, claim_type, category, status, published_at, featured) values
('what-is-dharma','{"en":"What is Dharma?"}'::jsonb,'{"en":"The word everyone uses — and what it actually means in tradition."}'::jsonb,'{"en":"Dharma is among the oldest and most layered ideas in Indian thought. At its simplest it means \"that which upholds\" — the order, duty and righteousness that sustains a person and society.\n\nIn the Mahabharata and Puranas, dharma is contextual: the right action for a parent differs from that of a warrior or a priest. The Bhagavad Gita famously tells Arjuna to follow svadharma — one\u0027s own path of duty — rather than imitate another\u0027s.\n\nFor daily life, tradition frames dharma through practice: puja, seva (selfless service), truthful speech, care for elders, and remembrance of the divine. Pratha treats these as living practices you can participate in — not merely ideas to read about."}'::jsonb,'beginner','itihasa','traditional','Foundations','published', now(), true),
('why-diya','{"en":"Why do we light a diya?"}'::jsonb,'{"en":"The small flame at the heart of almost every Hindu ritual."}'::jsonb,'{"en":"Before most Hindu prayers a small lamp — a diya — is lit. Tradition reads the flame on several levels.\n\nThe Upanishadic imagination associates light with knowledge: the famous prayer asato mā sad gamaya, tamaso mā jyotir gamaya (\"lead me from untruth to truth, from darkness to light\"). Lighting a lamp marks the transition into a sacred moment.\n\nPractically, a flame focuses attention. Agni — fire — also carries offerings in Vedic ritual, so the lamp is a small household echo of the sacred fire. Many families light the lamp at dusk; the act is as much about pausing as it is about the flame itself."}'::jsonb,'beginner','temple_tradition','traditional','Rituals','published', now(), true),
('what-is-ekadashi','{"en":"What is Ekadashi?"}'::jsonb,'{"en":"The eleventh tithi — why millions fast twice a month."}'::jsonb,'{"en":"Ekadashi is the eleventh day of each fortnight of the lunar month, occurring twice a month. Vaishnava tradition especially honours it with fasting (vrata) and remembrance of Vishnu.\n\nPuranic texts such as the Padma Purana attach stories and merit to each Ekadashi. Practically, devotees observe it by fasting (fully or partially), extra prayer, and restraint — ending on Dwadashi, the following tithi.\n\nWhether one fasts or not, the calendar itself is the point: a rhythm of sacred time returning every fortnight."}'::jsonb,'beginner','purana','scriptural','Observances','published', now(), true)
on conflict (slug) do nothing;
